Load libraries and minimally clean data
```{r}
knitr::opts_chunk$set(cache=T)
library("ggplot2")
library("dplyr")
data <- read.csv("WorkDf5.csv", sep=";")
data$MEDperMonth <- ifelse(data$TimeBefore==0, 0, data$med_load/data$TimeBefore)
data$MEDperMonth <- ifelse(data$MEDperMonth > 80000, NA, data$MEDperMonth)
datagrp <- group_by(data, TKAYear)
data$TKAYear <- as.factor(data$TKAYear)
```

Graph: MEDperMonth by year 
```{r}
#Mean
meanMEDxYear <- summarise(datagrp, Mean_MED = mean(MEDperMonth, na.rm=T))
g <- ggplot(meanMEDxYear, aes(TKAYear, Mean_MED)) + geom_point() + geom_smooth(method = "lm", se = F) + labs(title = "Mean Preoperative Morphine Equivalents \n per Month by Year", x = "Year", y = "Mean Morphine Equivalents per Month")

#Median
medianMEDxYear <- summarise(datagrp, MEDperMonth = median(MEDperMonth, na.rm=T))
p <- ggplot(medianMEDxYear, aes(TKAYear, Median_MED)) + geom_point() + geom_smooth(method = "lm", se = F) + labs(title = "Median Preoperative Morphine Equivalents \n per Month by Year", x = "Year", y = "Median Morphine Equivalents per Month")

#Median graph with quartiles
p <- ggplot(data, aes(TKAYear, MEDperMonth)) + geom_boxplot(outlier.shape = NA, fill="aliceblue") + coord_cartesian(ylim = c(0,875))+geom_smooth(method="lm", aes(group=1))+ labs(title = "Preoperative Opiate Use by Year", x = "Year", y = "Distribution of Morphine Equivalents per Month")
```

Graph: TypeBefore by year
```{r}
#Mean
meanTBxYear <- summarise(datagrp, Mean_Types = mean(TypeBefore, na.rm=T))
a <- ggplot(meanTBxYear, aes(TKAYear, Mean_Types)) + geom_point() + geom_smooth(method = "lm", se = F) + labs(title = "Mean Number of Unique Opiates Prescribed \n Preoperatively by Year", x = "Year", y = "Mean Unique Opiates Prescribed")

#Median
medianTBxYear <- summarise(datagrp, Median_Types = median(TypeBefore, na.rm=T))
b <- ggplot(medianTBxYear, aes(TKAYear, Median_Types)) + geom_point() + geom_smooth(method = "lm", se = F) + labs(title = "Median Number of Unique Opiates Prescribed \n Preoperatively by Year", x = "Year", y = "Median Unique Opiates Prescribed")
```

Create graphs
```{r}
ppi <- 300
png("MeanMEDxYear.png", width = 6*ppi, height = 6*ppi, res = ppi)
g
dev.off()
pdf("MeanMEDxYear.pdf")
g
dev.off()
png("MedianMEDxYear.png", width = 6*ppi, height = 6*ppi, res = ppi)
p
dev.off()
pdf("MedianMEDxYear.pdf")
p
dev.off()
png("MeanTypeBeforexYear.png", width = 6*ppi, height = 6*ppi, res = ppi)
a
dev.off()
pdf("MeanTypeBeforexYear.pdf")
a
dev.off()
png("MedianTypeBeforexYear.png", width = 6*ppi, height = 6*ppi, res = ppi)
b
dev.off()
pdf("MedianTypeBeforexYear.pdf")
b
dev.off()
```

Age histogram, grouped by chronic opioid use
```{r}
data$chronic <- as.factor(data$chronic)
data <- rename(data, Chronic = chronic)
data$Chronic <- ifelse(data$Chronic == 1, "Yes", "No")
z <- ggplot(data, aes(x=Age, fill = Chronic)) + geom_histogram() + labs(title = "Age Distribution Grouped by Chronic \n Opiate Use", x = "Age", y = "Count")

#Save
ppi <- 300
png("AgexChronic.png", width = 6*ppi, height = 6*ppi, res = ppi)
z
dev.off()
pdf("AgexChronic.pdf")
z
dev.off()
```

Revision free survival curve separated by chronic opioid use with CIs and p-value
```{r}
library("survival")
library("rms")
data$chronic <- ifelse(data$chronic == 1, "Chronic", "Not Chronic")
data$chronic <- as.factor(data$chronic)
data$t2rev <- ifelse(data$t2rev < 0, NA, data$t2rev)
data2 <- na.omit(data[,c(39,48,49)])
data2$RevLogical <- as.logical(ifelse(data2$RevLogical == 0, F, T))
fit <- survdiff(Surv(data2$t2rev, data2$RevLogical) ~ data2$chronic)
fit #gives p-value
objNpsurv <- npsurv(formula = Surv(t2rev, RevLogical == 1) ~ chronic, data = data2)
ppi <- 300
png("Survival.png", width = 6*ppi, height = 6*ppi, res = ppi)
survplot(objNpsurv, ylim = c(.9,1), xlab = "Days", ylab = "Percent of TKAs Unrevised", conf.type="log-log", levels.only=T, col.fill =c(7,6), legend.pos="right")
title(main = "Survival Curve of TKA Revision by Opiate Use")
text(2100, .98, "P = 1.71 x10^-11")
dev.off()
pdf("Survival.pdf")
survplot(objNpsurv, ylim = c(.9,1), xlab = "Days", ylab = "Percent of TKAs Unrevised", conf.type="log-log", levels.only=T, col.fill =c(7,6), legend.pos="right")
title(main = "Survival Curve of TKA Revision by Opiate Use")
text(2100, .98, "P = 1.71 x10^-11")
dev.off()
```

Surface plot: x = MED/Month, y = TimeBefore, z = count
```{r}
#Prepare data
library(MASS)
library(RColorBrewer)
library(hexbin)
rf <- colorRampPalette(rev(brewer.pal(11,'Spectral')))
r <- rf(32)
data$MEDperMonth <- ifelse(data$TimeBefore==0, 0, data$med_load/data$TimeBefore)
data$MEDperMonth <- ifelse(data$MEDperMonth > 80000, NA, data$MEDperMonth) #Remove outliers
data <- mutate(data, MEDperDay = MEDperMonth/(365/12))
data2 <- na.omit(data[,c(51,19)])
data3 <- data2[data2$TimeBefore > 2 & data2$MEDperDay >=2,] #Only graph chronic opiate users

#ggplot version of graph
p <- ggplot(data3, aes(MEDperDay,TimeBefore))
h3 <- p + stat_bin2d(bins=50) + scale_fill_gradientn(colours=r) + labs(title="Density Plot of Preop Morphine Equivalent \n Use in Chronic Users", x="Morphine Equivalents/ Day", y="Months")
h3

#hexbin version of graph
hexbinplot(TimeBefore ~ MEDperDay, data=data3, colramp=rf, trans=log, inv=exp)

#KDE2D version of graph
k <- kde2d(data3[,1], data3[,2], n=200, lims=c(0,75,3,30))
#Pretty
image(k, col=r, ylim=c(0,30))
#Less pretty
filled.contour(k,color.palette=colorRampPalette(c('white','blue','yellow','red','darkred')), ylim=c(0,25), xlim=c(0,50))

#Code to save KDE2D version of graph
ppi <- 300
png("Density.png", width = 6*ppi, height = 6*ppi, res = ppi)
image(k, col=r, ylim=c(0,30))
title(main="(b)", xlab = "Morphine Equivalents / Day", ylab = "Months")
dev.off()
pdf("Density.pdf")
image(k, col=r, ylim=c(0,30))
title(main="(b)", xlab = "Morphine Equivalents / Day", ylab = "Months")
dev.off()

#Add Histograms
hist(data3$MEDperDay, breaks = seq(2,2500,2), freq = F, xlim = c(2,73), main = "(a)", xlab = "Morphine Equivalents/ Day", ylab = "Percent of Chronic Opiate Users", xaxt="n", col = "grey", ylim=c(0,.1))
axis(1, at=c(0,10,20,30,40,50,60,70))

A <- hist(data3$TimeBefore, breaks = seq(3,71,2), freq = F, xlim = c(0,29))
plot(NULL, type = "n", xlim = c(0, max(A$density)), ylim = c(0,30),main = "(c)", ylab = "Months", xlab = "Percent of Chronic Opiate Users")
rect(0, A$breaks[1:(length(A$breaks) - 1)], A$density, A$breaks[2:length(A$breaks)], col = "grey")

#Images together
layout(matrix(c(3,4,1,2),2,2,byrow=T))
image(k, col=r, ylim=c(0,30))
title(main="(b)", xlab = "Morphine Equivalents / Day", ylab = "Months")

plot(NULL, type = "n", xlim = c(0, max(A$density)), ylim = c(0,30),main = "(c)", ylab = "Months", xlab = "Percent of Chronic Opiate Users")
rect(0, A$breaks[1:(length(A$breaks) - 1)], A$density, A$breaks[2:length(A$breaks)], col = "grey")

hist(data3$MEDperDay, breaks = seq(2,2500,2), freq = F, xlim = c(2,73), main = "(a)", xlab = "Morphine Equivalents/ Day", ylab = "Percent of Chronic Opiate Users", xaxt="n", col = "grey", ylim=c(0,.1))
axis(1, at=c(0,10,20,30,40,50,60,70))
```

Devision scatterplot
```{r}
library("ggplot2")
library("dplyr")
data <- read.csv("WorkDf5.csv", sep=";")
data <- data[,c(11,19,39,47)]
data$MEDperMonth <- ifelse(data$TimeBefore==0, 0, data$med_load/data$TimeBefore)
data$MEDperMonth <- ifelse(data$MEDperMonth > 80000, NA, data$MEDperMonth)
data <- mutate(data, MEDperDay = MEDperMonth/(365/12))
data <- mutate(data, Chronic = ifelse(TimeBefore > 2 & MEDperDay >= 2, 1, 0))
data <- na.omit(data[,c(1,3,6,7)])
datagrp <- group_by(data, DIVISION)
points <- summarize(datagrp, Count = n(), Rev_Rate = sum(RevLogical)/n(), Med_MED = median(MEDperDay), Chron_Rate = sum(Chronic)/n())
points <- points[points$Count > 49,]
meanMED <- mean(points$Med_MED)
sdMED <- sd(points$Med_MED)
vert <- meanMED + (2 * sdMED)  
meanRev <- mean(points$Rev_Rate) 
sdRev <- sd(points$Rev_Rate)
hor <- meanRev + (2 * sdRev)  

#Plot
p <- ggplot(points, aes(Med_MED, Rev_Rate))
p + geom_hline(aes(yintercept=hor), color = "blue", linetype = 2) + geom_vline(aes(xintercept=vert), color = "blue", linetype = 2) + geom_point(aes(colour = Chron_Rate), size = 5) + scale_colour_gradient(high = "red", breaks =c(.1,.2,.3,.4,.5), guide = guide_legend(title = "Chronic Opiate \n Use Rate", reverse = T, keywidth = 3)) + theme_bw() + labs(title = "Opiate Use and TKA Revision for Each VAMC Division", x = "Median Daily Morphine Equivalents", y = "TKA Revision Rate") + annotate("text", x = (vert+.55), y = (hor+.002), colour = "blue", label = "Mean + 2 SD") 
```
